from __future__ import annotations

import argparse
import json
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path

from backup_core import DEFAULT_DOWNLOAD_WORKERS, DEFAULT_MIN_IMAGE_BYTES, backup_images, sanitize_drive_folder_name

DEFAULT_DRIVE_PARENT_ID = "1SJ30EQNzc6ha-JgHciww9kQ7gmqJwfNp"
LOCAL_TIMEZONE = timezone(timedelta(hours=8))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Back up all blog post images to Google Drive and update blog_posts.json.")
    parser.add_argument(
        "--input-json",
        default="blog_posts.json",
        help="Input JSON path generated by scrape_blog_posts.py.",
    )
    parser.add_argument(
        "--drive-parent-id",
        default=os.getenv("GOOGLE_DRIVE_PARENT_ID", DEFAULT_DRIVE_PARENT_ID),
        help="Optional Google Drive parent folder ID.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Zero-based start index for resume support.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Optional max number of posts to process.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-run backup even if drive_folder_link already exists.",
    )
    parser.add_argument(
        "--min-image-bytes",
        type=int,
        default=int(os.getenv("MIN_IMAGE_BYTES", str(DEFAULT_MIN_IMAGE_BYTES))),
        help="Skip images smaller than this many bytes.",
    )
    parser.add_argument(
        "--max-download-workers",
        type=int,
        default=int(os.getenv("MAX_DOWNLOAD_WORKERS", str(DEFAULT_DOWNLOAD_WORKERS))),
        help="Concurrent download workers per article.",
    )
    return parser.parse_args()


def load_posts(input_path: Path) -> list[dict[str, object]]:
    return json.loads(input_path.read_text(encoding="utf-8"))


def save_posts(output_path: Path, posts: list[dict[str, object]]) -> None:
    output_path.write_text(json.dumps(posts, ensure_ascii=False, indent=2), encoding="utf-8")


def safe_print(message: str) -> None:
    print(message.encode("cp950", errors="replace").decode("cp950"))


def now_local_iso() -> str:
    return datetime.now(LOCAL_TIMEZONE).isoformat(timespec="seconds")


def main() -> None:
    args = parse_args()
    repo_dir = Path(__file__).resolve().parent
    input_path = Path(args.input_json)
    if not input_path.is_absolute():
        input_path = repo_dir / input_path

    posts = load_posts(input_path)
    share_with_anyone = True
    processed = 0
    eligible_indexes = [
        idx
        for idx, post in enumerate(posts)
        if idx >= args.start_index and (args.force or not post.get("drive_folder_link"))
    ]
    if args.limit is not None:
        eligible_indexes = eligible_indexes[: args.limit]
    total_to_process = len(eligible_indexes)

    safe_print(f"Input JSON: {input_path}")
    safe_print(f"Drive parent ID: {args.drive_parent_id or '(none)'}")
    safe_print(f"Posts queued: {total_to_process}")
    safe_print(f"Min image bytes: {args.min_image_bytes}")
    safe_print(f"Max download workers: {args.max_download_workers}")

    for index, post in enumerate(posts):
        if index < args.start_index:
            continue
        if args.limit is not None and processed >= args.limit:
            break

        title = str(post["title"])
        url = str(post["url"])
        existing_link = post.get("drive_folder_link")
        if existing_link and not args.force:
            continue

        folder_name = sanitize_drive_folder_name(title, str(post.get("slug") or url))
        post["drive_folder_name"] = folder_name
        post["backup_started_at"] = now_local_iso()
        safe_print(f"[{processed + 1}/{total_to_process}] START {title}")
        safe_print(f"[{processed + 1}/{total_to_process}] URL {url}")
        safe_print(f"[{processed + 1}/{total_to_process}] FOLDER {folder_name}")

        try:
            result = backup_images(
                url=url,
                drive_folder_name=folder_name,
                drive_parent_id=args.drive_parent_id,
                share_with_anyone=share_with_anyone,
                upload_to_drive=True,
                upload_manifest=False,
                min_image_bytes=args.min_image_bytes,
                max_download_workers=args.max_download_workers,
                repo_dir=repo_dir,
            )
            cleanup = result.get("cleanup")
            post["image_count"] = result["image_count"]
            post["drive_folder_id"] = result["drive_folder_id"]
            post["drive_folder_link"] = result["drive_folder_link"]
            post["backup_status"] = "success"
            post["backup_error"] = None
            post["backup_finished_at"] = now_local_iso()
            if cleanup is not None:
                cleanup.cleanup()
        except Exception as exc:  # noqa: BLE001
            post["backup_status"] = "failed"
            post["backup_error"] = str(exc)
            post["backup_finished_at"] = now_local_iso()
        save_posts(input_path, posts)
        if post["backup_status"] == "success":
            safe_print(f"[{processed + 1}/{total_to_process}] OK {title} -> {post['drive_folder_link']}")
        else:
            safe_print(f"[{processed + 1}/{total_to_process}] FAIL {title} -> {post['backup_error']}")
        processed += 1

    safe_print(f"Processed {processed} post(s)")
    safe_print(f"Updated: {input_path}")


if __name__ == "__main__":
    main()
